AWSTemplateFormatVersion: 2010-09-09
Description: >-
  torrent-check-serverless
Transform:
  - AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
    Default: dev  
  SQSUrl: 
    Type: String
    Default: https://sqs.eu-west-1.amazonaws.com/836783797541/torrent-checked  
Resources:
  SQSQueueTransmission:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: 
        !Join
          - '-'
          - - 'torrent-check'
            - !Ref Environment
  SQSQueueTransmissionChecked:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:  
        !Join
          - '-'
          - - 'torrent-checked'
            - !Ref Environment
  TorrentCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Check SQS message to convert torrent to magnet and return to another SQS.
      Runtime: nodejs14.x
      FunctionName:  
        !Join
          - '-'
          - - 'torrent-check'
            - !Ref Environment      
      Handler: src/handlers/torrent-check-function.handler
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              "Fn::GetAtt":
                - SQSQueueTransmission
                - Arn
            BatchSize: 1
      Environment:
        Variables:
          SQS_QUEUE_URL: 
            !Join
              - '-'
              - - !Ref SQSUrl
                - !Ref Environment            
      MemorySize: 128
      Timeout: 25 
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::836783797541:policy/SqsTorrentCheckedSendMessage      

